apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-health-discovery
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: health-discovery
                port:
                  number: 8080