apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      imagePullSecrets:
      - name: averbis-docker-registry
      containers:
        - image: registry.averbis.com/kafka/averbis-kafka-broker:0.0.6
          name: broker
          ports:
            - containerPort: 9092
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/kafka/
              name: brokervol
      hostname: broker
      restartPolicy: Always
      volumes:
        - name: brokervol
          persistentVolumeClaim:
            claimName: brokervol

status: {}
