apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: zookeeper
    spec:
      imagePullSecrets:
      - name: averbis-docker-registry
      containers:
        - image: registry.averbis.com/kafka/averbis-kafka-zookeeper:0.0.6
          name: zookeeper
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /data/zookeeper
              name: zookeepervol
      hostname: zookeeper
      restartPolicy: Always
      volumes:
        - name: zookeepervol
          persistentVolumeClaim:
            claimName: zookeepervol

status: {}
