{{ if not .Values.existingDbSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace "database-secret" }}
data:
  {{- if $previous }}
  databaseRootPassword: {{ $previous.data.databaseRootPassword }}
  databasePassword: {{ $previous.data.databasePassword }}
  databaseUsername: {{ $previous.data.databaseUsername }}
  {{- else }}
  databaseRootPassword: {{ randAlphaNum 15 | b64enc | quote }}
  databasePassword: {{ randAlphaNum 15 | b64enc | quote }}
  databaseUsername: {{ "averbis" | b64enc | quote }}
  {{- end }}
{{ end }}
